spring.application.name=Spring-boot-user-rest-api

spring.datasource.url=jdbc:mysql://localhost:3306/tata
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create

